### ISSUE TITLE
Windows Defender Popup

### ISSUE THREAD

**Issue by ORB-Aerospace911** [smallketchup82/GalaxypediaDesktop#1]
Windows defender flags the software when first running the exe. May ward off some skeptical players. \/(._.)\/

**Comment by smallketchup82** [comment]
I'm pretty sure you have to pay for a certificate in order for that to not happen, but I could look into it anyways

**Comment by smallketchup82** [comment]
> I'm pretty sure you have to pay for a certificate in order for that to not happen, but I could look into it anyways

I was wrong about this, apparently windows defender smartscreen works off a reputation system, an app is considered well-known if it is installed and used by a certain amount of windows users. I don't think there's any way to get this app whitelisted.

[https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview](url)
