### ISSUE TITLE
Clicking on discord server link leaves me with a blank windows after i click continue to discord

### ISSUE THREAD

**Issue by ORB-Aerospace911** [smallketchup82/GalaxypediaDesktop#2]
![image](https://user-images.githubusercontent.com/79132854/171900177-9c46008c-e46c-4de7-a472-fb92c612975c.png)

**Comment by smallketchup82** [comment]
I think I should consider making those links open in your browser instead of the application

**Comment by smallketchup82** [comment]
fixed in 9ed43b05b173d32fa819c919a621481308e54166
